---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc vars
      include_vars: var/vars

    - name: create a vpc
      ec2_vpc_net:
         name: "{{vpc_name}}"
         cidr_block: "{{vpccidr}}"
         region: "{{region}}"
         dns_support: yes
         dns_hostnames: yes
         tenancy: default
         state: "{{state}}"
      register: vpc_out

    - name: create a public_subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        az: "{{zone}}"
        cidr: "{{pubsubnet}}"
        map_public: yes
      register: pubsubout


    - name: create a pvtsubnet
      ec2_vpc_subnet:
         vpc_id: "{{vpc_out.vpc.id}}"
         region: "{{region}}"
         az: "{{zone}}"
         state: "{{state}}"
         cidr: "{{pvtsubnet}}"
      register: pvtsubout

    - name: create a internetgateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
      register: igwout

    - name: create a pub route_table
      ec2_vpc_route_table:
         vpc_id: "{{vpc_out.vpc.id}}"
         region: "{{region}}"
         subnets:
            - "{{pubsubout.subnet.id}}"
         routes:
           - dest: 0.0.0.0/0
             gateway_id: "{{igwout.gateway_id}}"
      register: punRT_out








