---
- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - vars.yml
  tasks:
  - name: create a vpc
    ec2_vpc_net:
       name: "{{ vpc_name }}"
       cidr_block: "{{ vpccidrblock }}"
       region: "{{ region }}"
       # enable dns support
       dns_support: yes
       # enable dns hostname
       dns_hostname: yes
       tenancy: default
       state: "{{ state }}"
       tags:
         Name: "{{ vpcname }}"
    register: ec2_vpc_net_result

