---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc vars
      include_vars: var/vars

    - name: create a vpc
      ec2_vpc_net:
         name: "{{vpc_name}}"
         cidr_block: "{{vpccidr}}"
         region: "{{region}}"
         dns_support: yes
         dns_hostnames: yes
         tenancy: default
         state: "{{state}}"
      register: vpcout

    - name: create a pubsubnet
      ec2_vpc_subnet:
         vpc_id: "{{vpcout.vpc.id}}"
         region: "{{region}}"
         az: "{{zone}}"
         state: "{{state}}"
         cidr: "{{pubsubnet}}"
         map_public: yes
      register: pubsubout

    - name: create a pvtsubnet
      ec2_vpc_subnet:
         vpc_id: "{{vpc_out.vpc.id}}"
         region: "{{region}}"
         az: "{{zone}}"
         state: "{{state}}"
         cidr: "{{pvtsubnet}}"
         tags:
           Name: pvt_subnet
      register: pvtsubout

    - name: create a internetgateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
          Name: vprofileigw
      register: igwout

    - name: create a pub route_table
      ec2_vpc_route_table:
         vpc_id: "{{vpc_out.vpc.id}}"
         region: "{{region}}"
         subnets:
            - "{{pubsubout.subnet.id}}"
         routes:
           - dest: 0.0.0.0/0
             gateway_id: "{{igwout.gateway_id}}"
         tags:
           Name: vprofilepubRT
      register: punRT_out

    - name: create a natgateway
      ec2_vpc_nat_gateway:
       state: "{{state}}"
       region: "{{region}}"
       subnet_id: "{{pubsubout.subnet.id}}"
       wait: yes
       if_exist_do_not_create: true
       tags:
         Name: vprofileNatIgw
      register: natgatewatout

    - name: create a pvt routetable
      ec2_vpc_route_table:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        subnets:
           - "{{pvtsubout.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{natgatewatout.nat_gateway_id}}"
        tags:
          Name: vprofileprivateRT
      register: pvtRT

    - debug:
         var: "{{item}}"
      loop:
           -  vpc_out.vpc.id
           -  pvtsubout.subnet.id
           -  pubsubout.subnet.id
           -  igwout.gateway_id
           -  natgatewatout.nat_gateway_id